lsi: false
safe: true
source: [https://github.com/KwKKei/DSC180A-Methodology-5]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: minima
title: Methodology Assignment 5
description: Barebones static site for DSC180A-Methodology-5